/** @type {import('tailwindcss').Config} */
// Tokens originate from the Stitch design spec; light neutral palette and system type for the Apple-style redesign.
const sans = [
  '-apple-system',
  'BlinkMacSystemFont',
  'SF Pro Text',
  'Segoe UI',
  'system-ui',
  'sans-serif',
]

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'error-container': '#fde8ea',
        'surface-variant': '#e0e0e6',
        'secondary-container': '#005c3e',
        'on-surface-variant': '#6e6e73',
        'primary-fixed': '#ffdad2',
        'surface-container-high': '#e8e8ed',
        'inverse-surface': '#fbf6f2',
        'on-primary-container': '#ffffff',
        'surface-container-low': '#ffffff',
        background: '#f5f5f7',
        'primary-container': '#0071e3',
        primary: '#0066cc',
        'on-secondary': '#003824',
        'on-tertiary-fixed-variant': '#584400',
        'surface-tint': '#0066cc',
        'inverse-primary': '#ae3115',
        'tertiary-container': '#d2a501',
        'surface-container': '#f0f0f3',
        'on-error-container': '#7a0010',
        'on-surface': '#1d1d1f',
        'outline-variant': '#d2d2d7',
        'on-error': '#690005',
        'on-primary-fixed': '#3d0600',
        'on-tertiary': '#3d2e00',
        secondary: '#1a7f4b',
        'primary-fixed-dim': '#ffb4a3',
        'on-secondary-container': '#86d2ac',
        'tertiary-fixed-dim': '#f0c12c',
        error: '#d70015',
        'surface-container-highest': '#e0e0e6',
        'inverse-on-surface': '#352f2c',
        'on-tertiary-container': '#503d00',
        'on-secondary-fixed': '#002114',
        'tertiary-fixed': '#ffdf90',
        'on-secondary-fixed-variant': '#005236',
        'on-primary-fixed-variant': '#8c1900',
        outline: '#86868b',
        'surface-container-lowest': '#ffffff',
        'secondary-fixed-dim': '#89d6af',
        surface: '#f5f5f7',
        tertiary: '#b25000',
        'on-primary': '#ffffff',
        'on-background': '#1d1d1f',
        'secondary-fixed': '#a5f3ca',
        'surface-dim': '#f5f5f7',
        'on-tertiary-fixed': '#241a00',
        'surface-bright': '#ececf0',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'space-sm': '0.5rem',
        'gutter-sm': '0.75rem',
        gutter: '1rem',
        'margin-lg': '1.5rem',
        'space-xl': '1.75rem',
        'space-md': '0.75rem',
        margin: '1rem',
        'space-xs': '0.25rem',
        'space-lg': '1.25rem',
      },
      fontFamily: {
        'body-lg': sans,
        'body-md': sans,
        'label-sm': sans,
        'display-lg': sans,
        'body-sm': sans,
        'headline-lg': sans,
        'headline-md': sans,
        'label-lg': sans,
        'headline-sm': sans,
        'label-md': sans,
        'display-lg-mobile': sans,
      },
      fontSize: {
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '500' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-sm': ['10px', { lineHeight: '14px', letterSpacing: '0.05em', fontWeight: '700' }],
        'display-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.03em', fontWeight: '700' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'headline-lg': ['28px', { lineHeight: '34px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['22px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-lg': ['14px', { lineHeight: '18px', letterSpacing: '0.02em', fontWeight: '700' }],
        'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.03em', fontWeight: '700' }],
        'display-lg-mobile': ['32px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}
