/** @type {import('tailwindcss').Config} */
// Ported verbatim from the Stitch design spec (tailwind.config inline block).
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'error-container': '#93000a',
        'surface-variant': '#3a3430',
        'secondary-container': '#005c3e',
        'on-surface-variant': '#e1bfb8',
        'primary-fixed': '#ffdad2',
        'surface-container-high': '#2e2926',
        'inverse-surface': '#ebe0db',
        'on-primary-container': '#661000',
        'surface-container-low': '#201b18',
        background: '#171210',
        'primary-container': '#ff6b4a',
        primary: '#ffb4a3',
        'on-secondary': '#003824',
        'on-tertiary-fixed-variant': '#584400',
        'surface-tint': '#ffb4a3',
        'inverse-primary': '#ae3115',
        'tertiary-container': '#d2a501',
        'surface-container': '#241f1b',
        'on-error-container': '#ffdad6',
        'on-surface': '#ebe0db',
        'outline-variant': '#59413c',
        'on-error': '#690005',
        'on-primary-fixed': '#3d0600',
        'on-tertiary': '#3d2e00',
        secondary: '#89d6af',
        'primary-fixed-dim': '#ffb4a3',
        'on-secondary-container': '#86d2ac',
        'tertiary-fixed-dim': '#f0c12c',
        error: '#ffb4ab',
        'surface-container-highest': '#3a3430',
        'inverse-on-surface': '#352f2c',
        'on-tertiary-container': '#503d00',
        'on-secondary-fixed': '#002114',
        'tertiary-fixed': '#ffdf90',
        'on-secondary-fixed-variant': '#005236',
        'on-primary-fixed-variant': '#8c1900',
        outline: '#a88a83',
        'surface-container-lowest': '#120d0b',
        'secondary-fixed-dim': '#89d6af',
        surface: '#171210',
        tertiary: '#f0c12c',
        'on-primary': '#630f00',
        'on-background': '#ebe0db',
        'secondary-fixed': '#a5f3ca',
        'surface-dim': '#171210',
        'on-tertiary-fixed': '#241a00',
        'surface-bright': '#3e3834',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'space-sm': '0.5rem',
        'gutter-sm': '0.75rem',
        gutter: '1rem',
        'margin-lg': '1.5rem',
        'space-xl': '1.75rem',
        'space-md': '0.75rem',
        margin: '1rem',
        'space-xs': '0.25rem',
        'space-lg': '1.25rem',
      },
      fontFamily: {
        'body-lg': ['Plus Jakarta Sans', 'sans-serif'],
        'body-md': ['Plus Jakarta Sans', 'sans-serif'],
        'label-sm': ['Space Grotesk', 'sans-serif'],
        'display-lg': ['Space Grotesk', 'sans-serif'],
        'body-sm': ['Plus Jakarta Sans', 'sans-serif'],
        'headline-lg': ['Space Grotesk', 'sans-serif'],
        'headline-md': ['Space Grotesk', 'sans-serif'],
        'label-lg': ['Space Grotesk', 'sans-serif'],
        'headline-sm': ['Space Grotesk', 'sans-serif'],
        'label-md': ['Space Grotesk', 'sans-serif'],
        'display-lg-mobile': ['Space Grotesk', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '500' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-sm': ['10px', { lineHeight: '14px', letterSpacing: '0.05em', fontWeight: '700' }],
        'display-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.03em', fontWeight: '700' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'headline-lg': ['28px', { lineHeight: '34px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['22px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-lg': ['14px', { lineHeight: '18px', letterSpacing: '0.02em', fontWeight: '700' }],
        'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.03em', fontWeight: '700' }],
        'display-lg-mobile': ['32px', { lineHeight: '38px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}
